### ISSUE TITLE
plugins for coord info and aoi - no error if change to v 2.5

### ISSUE THREAD

**Issue by Pewillia** [fgpv-vpgf/fgpa-apgf#508] opened 2019-11-12 16:33 UTC
The plugins for area of interest and coord info don't cause an error if selected using v 3.2 and switch back to v 2.5, can still  do a preview and doesn't say they ares valid when validate. The plugin tab is there but  they aren't active with  2,5  so you can switch to v3.2 but don't say aren't used, Plugin in tab still appears with v2.5. Could we say plugin inactive with v.2.3.

**Comment by jolevesq** [comment] 2019-11-13 14:25
I think this is expected behavior. In version 2.5, they will never appear and we do not want the viewer to not validate. The plugin section will be inside the config but viewer will not initialize them. It is ok to do this.

The tab appears because it doesn`t behaves the same way as the form. I think we can let this for now because we will soon switch to version 3.2 in production so this thing will not be an issue anymore.

**Closed by jolevesq** 2019-11-13 14:25 UTC
